export const defaultSiteContent = {
  navigation: {
    main: [
      { label: "الوكالة", href: "/" },
      { label: "تسوق", href: "/market" },
      { label: "ميديا", href: "/media" },
      { label: "تك", href: "/tech" },
    ],
    topLinks: {
      aboutLabel: "من نحن",
      aboutHref: "/about",
      worksLabel: "أعمالنا",
      worksHref: "#",
      consultationLabel: "استشارة مجانية",
      consultationHref: "/consultation",
    },
  },
  footer: {
    quickLinks: [
      { label: "من نحن", href: "/about" },
      { label: "أعمالنا", href: "#" },
      { label: "دراسات الحالة", href: "#" },
      { label: "آراء العملاء", href: "#" },
      { label: "تواصل معنا", href: "/consultation" },
    ],
    services: [
      "استراتيجية السوق",
      "أبحاث النمو",
      "العلامة التجارية",
      "التسويق الرقمي",
      "تطوير المواقع",
      "تطبيقات الجوال",
    ],
    description:
      "شريكك المتكامل للنمو يجمع بين الاستراتيجية والإبداع والتكنولوجيا لتحقيق نتائج استثنائية.",
    contact: {
      email: "hello@agency.com",
      phone: "+966 50 000 0000",
      address: "الرياض - المملكة العربية السعودية",
    },
    copyrights: "© 2026 Agency. جميع الحقوق محفوظة.",
    privacyText: "سياسة الخصوصية",
    termsText: "شروط الاستخدام",
    poweredByText: "Powered by Readdy",
  },
  pages: {
    home: {
      hero: {
        badge: "وكالة رقمية متكاملة",
        titleLine1: "نصنع لك",
        titleHighlight: "حضوراً رقمياً",
        titleLine3: "لا يُنسى",
        description:
          "ثلاث شركات متخصصة تحت سقف واحد - استراتيجية، إبداع، وتقنية. نحوّل رؤيتك إلى واقع رقمي يتفوق على المنافسة.",
        primaryCta: "ابدأ مشروعك الآن",
        secondaryCta: "شاهد أعمالنا",
      },
    },
    agency: {
      portfolio: {
        badge: "معرض الأعمال",
        title: "أعمال نفتخر بإنجازها",
        subtitle:
          "نماذج من مشاريعنا الناجحة التي ساعدت عملاءنا على تحقيق أهدافهم وتجاوز توقعاتهم بنتائج استثنائية.",
        viewAllLabel: "عرض جميع الأعمال",
        filters: [
          { id: "all", label: "الكل" },
          { id: "market", label: "ماركت" },
          { id: "media", label: "ميديا" },
          { id: "tech", label: "تك" },
        ],
        projects: [
          {
            id: 1,
            category: "market",
            categoryLabel: "ماركت",
            client: "جلوبال ريتيل",
            title: "استراتيجية دخول السوق الإقليمية",
            description: "تطوير استراتيجية شاملة لدخول أسواق جديدة في المنطقة مع دراسة تنافسية معمقة.",
            duration: "6 أشهر",
            image: "/media-assets/portfolio-boardroom.png",
          },
          {
            id: 2,
            category: "media",
            categoryLabel: "ميديا",
            client: "تك ستارت",
            title: "حملة إطلاق العلامة التجارية الشاملة",
            description: "حملة تسويقية متكاملة لإطلاق علامة تجارية جديدة في السوق مع استراتيجية محتوى إبداعي.",
            duration: "3 أشهر",
            image: "/media-assets/portfolio-abstract.png",
          },
          {
            id: 3,
            category: "tech",
            categoryLabel: "تك",
            client: "فاشن فورورد",
            title: "منصة التجارة الإلكترونية المتكاملة",
            description: "تطوير منصة تجارة إلكترونية متكاملة مع نظام إدارة المخزون الذكي وتكامل مع بوابات الدفع المتعددة.",
            duration: "4 أشهر",
            image: "/media-assets/portfolio-ecommerce.png",
          },
          {
            id: 4,
            category: "market",
            categoryLabel: "ماركت",
            client: "فينتك سولوشنز",
            title: "تحليل وأبحاث السوق المالي",
            description: "دراسة شاملة للسوق المالي وتحليل المنافسين والفرص الاستثمارية.",
            duration: "3 أشهر",
            image: "/media-assets/portfolio-finance.png",
          },
          {
            id: 5,
            category: "media",
            categoryLabel: "ميديا",
            client: "إديوتك",
            title: "إنتاج محتوى فيديو تعليمي احترافي",
            description: "إنتاج سلسلة فيديوهات تعليمية احترافية للمنصة التعليمية مع رسوم متحركة.",
            duration: "4 أشهر",
            image: "/media-assets/portfolio-studio.png",
          },
          {
            id: 6,
            category: "tech",
            categoryLabel: "تك",
            client: "هيلث كير بلس",
            title: "تطبيق الجوال الصحي الذكي",
            description: "تطوير تطبيق جوال متقدم لإدارة المواعيد الطبية والسجلات الصحية الإلكترونية.",
            duration: "5 أشهر",
            image: "/media-assets/portfolio-mobile.png",
          },
          {
            id: 7,
            category: "market",
            categoryLabel: "ماركت",
            client: "إي-كومرس جلوبال",
            title: "استراتيجية التوسع الدولي",
            description: "تطوير خطة توسع دولية شاملة لدخول أسواق الخليج وشمال أفريقيا.",
            duration: "8 أشهر",
            image: "/media-assets/portfolio-map.png",
          },
          {
            id: 8,
            category: "media",
            categoryLabel: "ميديا",
            client: "ريتيل برو",
            title: "حملة إعلانية متعددة القنوات",
            description: "حملة إعلانية شاملة عبر منصات متعددة لزيادة المبيعات الموسمية.",
            duration: "2 أشهر",
            image: "/media-assets/portfolio-flowers.png",
          },
          {
            id: 9,
            category: "tech",
            categoryLabel: "تك",
            client: "ترافل هب",
            title: "منصة حجز السفر والسياحة",
            description: "تطوير منصة متكاملة لحجز الرحلات والفنادق مع نظام مقارنة الأسعار.",
            duration: "6 أشهر",
            image: "/media-assets/portfolio-travel.png",
          },
        ],
      },
      clientStories: {
        badge: "آراء العملاء",
        title: "حقيقة قصص نجاح",
        subtitle: "عملاؤنا هم أفضل دليل على جودة عملنا. إليك ما يقولونه عن تجربتهم معنا.",
        quote:
          "إبداع الفريق وتفكيرهم الاستراتيجي ساعدنا على إعادة بناء علامتنا التجارية وتوسيع أعمالنا بالكامل. هم لا ينفذون فقط - بل يفكرون كشركاء حقيقيين.",
        achievement: "توسع في 6 أسواق جديدة",
        authorName: "محمد العلي",
        authorRole: "المؤسس، فاشن فورورد",
        authorImage: "/media-assets/avatar-4.png",
        avatars: [
          "/media-assets/avatar-5.png",
          "/media-assets/avatar-2.png",
          "/media-assets/avatar-1.png",
          "/media-assets/avatar-4.png",
          "/media-assets/avatar-3.png",
        ],
        stats: [
          { value: "98%", label: "رضا العملاء" },
          { value: "4.9", label: "متوسط التقييم" },
          { value: "+200", label: "عميل سعيد" },
          { value: "90%", label: "معدل الاحتفاظ" },
        ],
      },
    },
    market: {
      caseStudies: {
        badge: "دراسات الحالة",
        title: "قصص نجاح عملائنا",
        subtitle: "نتائج حقيقية حققناها لشركات في مختلف الصناعات",
        tabs: [
          "شركة تقنية ناشئة",
          "شركة تجارة إلكترونية",
          "شركة خدمات B2B",
        ],
        metrics: [
          { value: "450%", label: "نمو الإيرادات" },
          { value: "12%", label: "حصة السوق" },
          { value: "+2,500", label: "عملاء جدد" },
        ],
        challengeTitle: "التحدي",
        challengeText: "دخول سوق جديد مع منافسة شديدة وميزانية محدودة.",
        solutionTitle: "الحل",
        solutionText: "استراتيجية تموضع فريدة وخطة دخول سوق مرحلية.",
        quote: "ساعدونا على تحقيق نمو لم نكن نتخيله. استراتيجيتهم كانت دقيقة وفعّالة.",
        authorName: "أحمد محمد",
        authorRole: "المدير التنفيذي - شركة تقنية ناشئة",
        authorImage: "/media-assets/avatar-4.png",
      },
      numbers: {
        badge: "نتائج حقيقية",
        title: "أرقام تتحدث عن نفسها",
        subtitle: "نتائج ملموسة حققناها لعملائنا",
        cards: [
          { title: "عائد الاستثمار", value: "4.5x", baseline: "1.2x", uplift: "+275%" },
          { title: "العملاء الجدد", value: "5,000", baseline: "500", uplift: "+900%" },
          { title: "الحصة السوقية", value: "17%", baseline: "2%", uplift: "+750%" },
          { title: "الإيرادات الشهرية", value: "200K", baseline: "50K", uplift: "+300%" },
        ],
        highlights: [
          { value: "+500", label: "مشروع ناجح" },
          { value: "98%", label: "رضا العملاء" },
          { value: "15+", label: "سنة خبرة" },
          { value: "3x", label: "متوسط النمو" },
        ],
      },
      faq: {
        badge: "الأسئلة الشائعة",
        title: "أسئلة قد تهمك",
        subtitle: "إجابات على الأسئلة الأكثر شيوعًا حول خدماتنا",
        items: [
          {
            id: "01",
            question: "ما الفرق بين خدمات ماركت وخدمات التسويق التقليدية؟",
            answer:
              "خدمات ماركت تركز على الاستراتيجية الشاملة للنمو، وليس فقط التنفيذ التسويقي. نبدأ بتحليل عميق للسوق والمنافسين ثم نبني خطة متكاملة تشمل التموضع، التسعير، القنوات، وخطة النمو.",
          },
          { id: "02", question: "كم من الوقت يستغرق رؤية النتائج؟", answer: "" },
          { id: "03", question: "هل تعملون مع الشركات الصغيرة أم الكبيرة فقط؟", answer: "" },
          { id: "04", question: "ما هي تكلفة خدماتكم؟", answer: "" },
          { id: "05", question: "هل تضمنون ضمان على النتائج؟", answer: "" },
          { id: "06", question: "هل تنفذون الاستراتيجية أم تقدمون الخطة فقط؟", answer: "" },
        ],
        ctaText: "لديك سؤال آخر؟ تواصل معنا مباشرة",
        ctaButton: "احجز استشارة مجانية",
      },
    },
    media: {
      services: {
        badge: "خدماتنا",
        title: "ماذا نقدم؟",
        subtitle: "مجموعة متكاملة من الخدمات الإبداعية لتحقيق جميع أهدافك التسويقية",
      },
      projects: {
        badge: "أعمالنا",
        title: "مشاريع مميزة",
        items: [
          { year: "2024", tag: "فيديو ترويجي", client: "تك إنوفيشن", title: "حملة إطلاق منتج تقني", statValue: "+250%", statLabel: "زيادة المبيعات", image: "/media-assets/project-phone.png", tone: "dark" },
          { year: "2025", tag: "إنتاج فيديو", client: "لوكس", title: "فيلم ترويجي لعطر فاخر", statValue: "+3.2M", statLabel: "مشاهدة", image: "/media-assets/project-cinema-2.png", tone: "dark" },
          { year: "2025", tag: "هوية بصرية", client: "إيكو هوم", title: "هوية مشروع عقاري", statValue: "+140%", statLabel: "نمو الوصول", image: "/media-assets/project-brand-2.png", tone: "light" },
          { year: "2024", tag: "إنتاج فيديو", client: "إيليجانس", title: "فيديو أزياء سينمائي", statValue: "+5M", statLabel: "مشاهدة", image: "/media-assets/project-fashion.png", tone: "dark" },
          { year: "2024", tag: "هوية بصرية", client: "لافيستا", title: "هوية مطعم فاخر", statValue: "+180%", statLabel: "نمو المتابعين", image: "/media-assets/project-brand.png", tone: "light" },
        ],
      },
      whyUs: {
        badge: "لماذا نحن",
        title: "خدماتنا الإعلامية؟",
        subtitle: "نجمع بين الإبداع والاستراتيجية لنقدّم لك حلولاً إعلامية متكاملة تحقق نتائج ملموسة.",
        stats: [
          { value: "320%", label: "متوسط العائد" },
          { value: "98%", label: "رضا العملاء" },
          { value: "200+", label: "عميل سعيد" },
          { value: "500+", label: "مشروع ناجح" },
        ],
        features: [
          { title: "إبداع لا محدود", description: "نفكر خارج الصندوق لكل مشروع" },
          { title: "فريق محترف", description: "خبراء في جميع مجالات الإعلام والتسويق" },
          { title: "نتائج سريعة", description: "نحقق أهدافك في أقصر وقت ممكن" },
          { title: "دعم مستمر", description: "نبقى معك في كل خطوة من الرحلة" },
        ],
      },
      faq: {
        badge: "الأسئلة الشائعة",
        title: "أسئلة قد تهمك",
        subtitle: "إجابات على الأسئلة الأكثر شيوعاً حول خدماتنا",
        items: [
          {
            id: "01",
            question: "ما الفرق بين خدمات ماركت وخدمات التسويق التقليدية؟",
            answer:
              "خدمات ماركت تركز على الاستراتيجية الشاملة للنمو، وليس فقط التنفيذ التسويقي. نبدأ بتحليل عميق للسوق والمنافسين، ثم نبني استراتيجية متكاملة تشمل التموضع، التسعير، القنوات، وخطة النمو.",
          },
          { id: "02", question: "كم من الوقت يستغرق رؤية النتائج؟", answer: "" },
          { id: "03", question: "هل تعملون مع الشركات الصغيرة أم الكبيرة فقط؟", answer: "" },
          { id: "04", question: "ما هي تكلفة خدماتكم؟", answer: "" },
          { id: "05", question: "هل تقدمون ضمان على النتائج؟", answer: "" },
          { id: "06", question: "هل تنفذون الاستراتيجية أم تقدمون الخطة فقط؟", answer: "" },
        ],
        ctaText: "لديك سؤال آخر؟ تواصل معنا مباشرة",
        ctaButton: "احجز استشارة مجانية",
      },
    },
    tech: {
      projectsSection: {
        title: "مشاريع غيرت قواعد اللعبة",
        subtitle: "نماذج واقعية من منتجات رقمية طورناها لقطاعات متعددة.",
        filters: [
          { id: "all", label: "الكل" },
          { id: "web", label: "مواقع" },
          { id: "mobile", label: "جوال" },
          { id: "ai", label: "ذكاء اصطناعي" },
        ],
        projects: [
          {
            id: "ecommerce",
            title: "منصة التجارة الإلكترونية",
            category: "web",
            categoryLabel: "ويب",
            description: "منصة تجارة إلكترونية متكاملة مع إدارة طلبات ومخزون.",
            year: "2024",
            image: "/media-assets/project-phone.png",
            metrics: [
              { value: "95%", label: "رضا العملاء" },
              { value: "80%", label: "نمو المبيعات" },
              { value: "250%", label: "زيادة الطلبات" },
            ],
          },
          {
            id: "delivery",
            title: "تطبيق التوصيل الفوري",
            category: "mobile",
            categoryLabel: "جوال",
            description: "تطبيق توصيل مع تتبع حي وتجربة مستخدم مبسطة.",
            year: "2024",
            image: "/media-assets/project-fashion.png",
            metrics: [
              { value: "40%", label: "سرعة التوصيل" },
              { value: "99%", label: "توفر الخدمة" },
              { value: "5000+", label: "عملية يومية" },
            ],
          },
          {
            id: "assistant",
            title: "مساعد ذكاء اصطناعي",
            category: "ai",
            categoryLabel: "AI",
            description: "مساعد ذكي لدعم القرارات وتحليل بيانات العملاء.",
            year: "2024",
            image: "/media-assets/project-brand.png",
            metrics: [
              { value: "94%", label: "دقة التحليل" },
              { value: "90%", label: "رضا الفريق" },
              { value: "85%", label: "توفير الوقت" },
            ],
          },
          {
            id: "dashboard",
            title: "نظام إدارة المستشفيات",
            category: "web",
            categoryLabel: "لوحة تحكم",
            description: "لوحة تشغيل مركزية لإدارة العمليات الطبية والبيانات.",
            year: "2023",
            image: "/media-assets/service-dashboard.png",
            metrics: [
              { value: "92%", label: "الكفاءة" },
              { value: "99%", label: "الاعتمادية" },
              { value: "60%", label: "توفير التكاليف" },
            ],
          },
        ],
      },
    },
    about: {
      hero: {
        badge: "من نحن",
        titleLine1: "فريق يصنع النمو",
        titleHighlight: "بعقلية تنفيذية واضحة",
        description:
          "نحن وكالة عربية تجمع الاستراتيجية، الإبداع، والتقنية في منظومة واحدة. هدفنا بسيط: نحول الرؤية إلى نتائج قابلة للقياس، بخطوات عملية وسرعة تنفيذ تواكب طموحك.",
        primaryCta: "احجز استشارة مجانية",
        secondaryCta: "استعرض أعمالنا",
      },
      valuesTitle: "كيف نفكر عندما نعمل معك",
      valuesSubtitle: "فلسفة عملنا توازن بين العمق الاستراتيجي والسرعة التنفيذية، حتى تحصل على نتائج ملموسة بدون تعقيد.",
      values: [
        { title: "وضوح استراتيجي", description: "نبني كل مشروع على أهداف واضحة ومؤشرات نجاح قابلة للقياس، بدون قرارات عشوائية." },
        { title: "تنفيذ متقن", description: "نركز على الجودة من أول نسخة، مع تفاصيل تصميم وتجربة مستخدم تعكس مستوى العلامة." },
        { title: "شراكة طويلة", description: "لا نعمل بعقلية تسليم فقط، بل نرافقك بعد الإطلاق لتوسيع الأثر وتحسين النتائج." },
        { title: "مرونة عالية", description: "نشكل فرق العمل وفق احتياجك الحقيقي: سريع عند الانطلاق، ومنهجي عند التوسع." },
      ],
      milestonesTitle: "محطاتنا",
      milestonesSubtitle: "رحلة متدرجة بنينا فيها منهجية تنفيذ موثوقة وقابلة للتوسع.",
      milestones: [
        { year: "2011", title: "البداية", description: "انطلاق الفريق الأساسي بخدمات بناء الهوية وتجارب المواقع." },
        { year: "2016", title: "توسع الخدمات", description: "إضافة فرق مستقلة للتسويق الرقمي، الإنتاج الإبداعي، والتقنية." },
        { year: "2021", title: "هيكلة الوكالة", description: "توحيد فرق التنفيذ تحت نموذج تشغيلي واحد سريع ومرن." },
        { year: "اليوم", title: "منظومة متكاملة", description: "نقود مشاريع نمو في قطاعات متعددة داخل السعودية وخارجها." },
      ],
      teamTitle: "قيادة المشروع",
      teamSubtitle: "فريق متعدد التخصصات يدير التفاصيل من الفكرة حتى الإطلاق.",
      leaders: [
        { name: "سارة خالد", role: "مديرة الاستراتيجية", image: "/media-assets/avatar-5.png" },
        { name: "أحمد فهد", role: "مدير التطوير", image: "/media-assets/avatar-4.png" },
        { name: "ريم العلي", role: "مديرة التسويق", image: "/media-assets/avatar-3.png" },
        { name: "محمد ناصر", role: "مدير المشاريع", image: "/media-assets/avatar-2.png" },
      ],
      finalCtaTitle: "جاهز تبني قصة نجاحك القادمة؟",
      finalCtaText: "نبدأ بجلسة استشارية سريعة لفهم احتياجك الحقيقي، ثم نضع لك خطة واضحة بالخطوات والأولويات.",
      finalCtaButton: "ابدأ الاستشارة المجانية",
    },
    consultation: {
      hero: {
        badge: "استشارة مجانية",
        titleLine1: "جلسة استراتيجية",
        titleHighlight: "تمنحك وضوحًا قبل التنفيذ",
        description:
          "إذا عندك مشروع جديد أو مشروع قائم يحتاج إعادة توجيه، هذه الجلسة تساعدك تشوف الصورة كاملة: الأولويات، الميزانية، والخطوات العملية المناسبة لمرحلتك.",
      },
      perks: [
        { value: "45 دقيقة", label: "جلسة مركزة" },
        { value: "خطة واضحة", label: "مخرجات عملية" },
        { value: "بدون التزام", label: "استشارة مجانية بالكامل" },
      ],
      form: {
        title: "احجز موعدك الآن",
        subtitle: "املأ النموذج وسيتواصل معك الفريق خلال 24 ساعة.",
        nameLabel: "الاسم الكامل",
        emailLabel: "البريد الإلكتروني",
        phoneLabel: "رقم الجوال",
        companyLabel: "اسم الشركة",
        serviceLabel: "الخدمة المطلوبة",
        detailsLabel: "وصف مختصر لاحتياجك",
        submit: "تأكيد طلب الاستشارة",
      },
      services: [
        "استراتيجية السوق والنمو",
        "تطوير الهوية والعلامة",
        "التسويق الرقمي",
        "تطوير موقع أو متجر",
        "تطبيقات الجوال",
        "خطة متكاملة (ماركت + ميديا + تك)",
      ],
      processTitle: "خطوات بسيطة ونتيجة واضحة",
      process: [
        { step: "01", title: "نفهم احتياجك", description: "نجمع التفاصيل الأساسية لنفهم وضعك الحالي وأهدافك." },
        { step: "02", title: "نشخص الفرص", description: "نحدد نقاط التحسين السريعة والفرص الأعلى أثرًا على النمو." },
        { step: "03", title: "نقترح خارطة طريق", description: "نضع لك مسارًا واضحًا بخطوات عملية، ميزانية، وأولويات التنفيذ." },
      ],
      finalCtaTitle: "تحتاج تفاصيل أكثر عن الوكالة؟",
      finalCtaText: "تعرف على طريقة عملنا وفريقنا والمنهج الذي نتبعه قبل بداية أي مشروع.",
      finalCtaButton: "زيارة صفحة من نحن",
    },
  },
} as const;

export type SiteContent = typeof defaultSiteContent;
